# Site configuration
# Add social networks

markdown: kramdown
highlighter: rouge
permalink: /:title/
baseurl: https://lukalafaye.github.io/Jekyll-MarkDown
encoding: UTF-8
sass:
    sass_dir: _sass

title: Title
description: Description of this blog

github: lukalafaye
facebook: lukalafaye
