# Site configuration

markdown: kramdown
highlighter: rouge
permalink: /:title/

# Change this URL to your website's
url: https://lukalafaye.github.io/Jekyll-MarkDown

encoding: UTF-8
sass:
    sass_dir: _sass

# Change Title
title: Title

# Change description
description: Description of this blog

#########################################
#        Add # sign to disable          #
#########################################

codepen: User
facebook: User
github: User
instagram: User
twitter: User
youtube: User
